---

- name: Install EPEL repo
  yum:
    name: epel-release
    state: present

- name: Write sshd banner
  copy:
    src: "sshd_banner"
    dest: "/etc/ssh/sshd_banner"
    owner: root
    group: root
    mode: u=rw

- name: Write sshd config
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: u=rw
  notify:
    - Restart sshd service

- name: Ensure sshd is enabled at boot time
  service:
    name: sshd
    enabled: yes
  tags:
    - medium
    - sshd
    - V-72235

- name: Determine existing public ssh host keys
  shell: ls /etc/ssh/*.pub
  register: public_ssh_host_keys
  # The shell command will always report 'changed' so we need to
  # ignore that since this role is supposed to be idempotent.
  changed_when: false
  check_mode: no
  tags:
    - always

- name: Public host key files must have mode 0644 or less
  file:
    path: "{{ item }}"
    mode: "u-xX,g-wxs,o-wxt"
  with_items:
    - "{{ public_ssh_host_keys.stdout_lines | default([]) }}"
  tags:
    - medium
    - sshd
    - V-72255

- name: Determine existing private ssh host keys
  shell: ls /etc/ssh/*_key
  register: private_ssh_host_keys
  # The shell command will always report 'changed' so we need to
  # ignore that since this role is supposed to be idempotent
  changed_when: false
  check_mode: no
  tags:
    - always

- name: Private host key files must have mode 0600 or less
  file:
    path: "{{ item }}"
    mode: "u-xX,g-rwxs,o-rwxt"
  with_items:
    - "{{ private_ssh_host_keys.stdout_lines | default([]) }}"
  tags:
    - medium
    - sshd
    - V-72257
