---

- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install MySQL RPM repository
  yum:
    name: "{{ mysql_repo_url }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Download MySQL DEB repository
  get_url:
    url: "{{ mysql_repo_url }}"
    dest: /tmp/mysql.deb
  when: ansible_os_family == "Debian"

- name: Install MySQL DEB repository
  apt:
    deb: /tmp/mysql.deb
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Update APT cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install MySQL server and Python library
  package:
    name: "{{ mysql_packages }}"
    state: present
  register: mysql_install

- name: Start MySQL server
  service:
    name: "{{ mysql_service }}"
    state: started
    enabled: yes

- name: Acquire temporary root pass
  shell: >
    awk '$0 ~ "temporary password" {print $13}' /var/log/mysqld.log
  become: yes
  register: mysql_root_temp_password
  when: mysql_install.changed and ansible_os_family == "RedHat"

- name: Add workaround for outdated Ansible module
  lineinfile:
    path: "{{ mysql_mycnf_path }}"
    line: default_authentication_plugin=mysql_native_password
    insertafter: "^[mysqld]"

- name: Test temporary root password expired
  shell: "mysql -NBe 'SELECT NOW();' -u root -p'{{ mysql_root_temp_password.stdout }}'"
  register: mysql_temp_password_test_result
  when: mysql_install.changed and ansible_os_family == "RedHat"
  ignore_errors: yes

- name: Update expired password for localhost account
  shell: >
      mysql -NBe 'ALTER USER "root"@"localhost" IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_temp_password.stdout }}";' 
      --connect-expired-password -u root -p'{{ mysql_root_temp_password.stdout }}'
  when: mysql_install.changed and ansible_os_family == "RedHat"

- name: Update mysql root password for local server accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    login_user: root
    login_password: "{{ mysql_root_temp_password.stdout }}"
    state: present
  with_items: "{{ mysql_hosts }}"
  when: mysql_install.changed and ansible_os_family == "RedHat"

- name: Update mysql root password for local server accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    state: present
  with_items: "{{ mysql_hosts }}"
  when: mysql_install.changed and ansible_os_family == "Debian"

- name: Deploy `/root/.my.cnf` with MySQL root credentials
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  notify: Restart MySQL

- name: Remove test database
  mysql_db:
    name: test
    state: absent

- name: Remove anonymous user accounts
  mysql_user:
    name: ""
    host_all: yes
    state: absent