---

- name: Install MySQL repository
  yum:
    name: "{{ mysql_repo_url }}"
    state: present

- name: Install MySQL server and Python library
  yum:
    name: [ "mysql-server", "MySQL-python"]
    state: present
  register: mysql_install

- name: Add workaround for outdated Ansible module
  lineinfile:
    path: /etc/my.cnf
    line: default_authentication_plugin=mysql_native_password
    insertafter: "^[mysqld]"

- name: Start MySQL server
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Acquire temporary root pass
  shell: >
    awk '$0 ~ "temporary password" {print $13}' /var/log/mysqld.log
  become: yes
  register: mysql_root_temp_password
  when: mysql_install.changed

- name: update mysql root password for all root accounts from local servers
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    login_user: root
    login_password: "{{ mysql_root_temp_password.stdout }}"
    state: present
  with_items: "{{ mysql_hosts }}"
  when: mysql_install.changed

- name: Deploy `/root/.my.cnf` with MySQL root credentials
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  notify: Restart MySQL

- name: Remove test database
  mysql_db:
    name: test
    state: absent

- name: Remove anonymous user accounts
  mysql_user:
    name: ""
    host_all: yes
    state: absent