---

- name: Install certbot
  yum:
    name: certbot
    state: present

- name: Check if certificate already exists
  stat:
    path: "/etc/letsencrypt/live/fleet.{{ project_domain }}/cert.pem"
  register: letsencrypt_cert

- name: Generate certificate with letsencrypt
  command: "certbot certonly --standalone --noninteractive --agree-tos --email {{ fleet_mail }} -d fleet.{{ project_domain }}"
  become: yes
  when: letsencrypt_cert.stat.exists == false