---

- name: Deploy Fleet service file
  template:
    src: fleet.service.j2
    dest: /etc/systemd/system/fleet.service
    owner: root
    group: root
    mode: u+rwx,g+rx,o+rx
  register: fleet_service_deployment

- name: Prepare Fleet database
  command: "fleet prepare db --mysql_address=127.0.0.1:3306 --mysql_database=kolide --mysql_username=fleet --mysql_password={{ fleet_mysql_user_password }}"
  when: fleet_service_deployment.changed

- name: Start Fleet service
  service:
    name: fleet
    state: started
    enabled: yes

- name: Confiugre Fleetctl
  command: "fleetctl config set --address https://fleet.{{ project_domain }} --rootca {{ fleet_configuration_directory }}/certificate.pem"
  when: fleet_service_deployment.changed

- name: Configure Fleet admin account
  command: "fleetctl setup --email {{ fleet_mail }} --password {{ fleet_password }}"
  when: fleet_service_deployment.changed