---

- hosts: all
  module_defaults:
    apt:
      force_apt_get: yes
  become: yes
  roles:
    - hardening

- hosts: fleet
  become: yes
  roles:
    - fleet

- hosts: grr
  module_defaults:
    apt:
      force_apt_get: yes
  become: yes
  roles:
    - grr